# Amazon EC2 Container Registry (ECR)
1. Create a repository 
- Login to your AWS Account and Navigate to EC2 Container Services >> Repositories >> Create Repositories >> Configure repository name <DevOps> >> Click Next Step >> Done
2. Connect to a repository 
[root@samal-dimdung3 ~]# aws ecr get-login --region us-east-1
docker login -u AWS -p AQECAHhwm0YaISJeRtJm5n1G6uqeekXuoXXPe5UFce9Rq8/14wAAAyEwggMdBgkqhkiG9w0BBwagggMOMIIDCgIBADCCAwMGCSqGSIb3DQEHATAeBglghkgBZQMEAS4wEQQMcHlukyUJnHfLg/hwAgEQgIIC1MjtXEs4sxF4FJQUZraUXfErgNuUA1o6TvH/DaZ9uimQ53uV+waHMllN9MPzdwPbg4t4Y9sTBT5GaHxffMV+x5ZHwNaAXN1NbIjk9ERS8ApbtEUfP2D+Hjcyf5qYTNsJa4bkIgLQN5Elpa2v2tXOsJACABqynBtl40x5WofZXl2TRPW0v6xJ1jHQJznrSmhL08VdXm3fOvSjJjSKcaPF1rL9Zh0KHioPG1oLQnEFH4RMQ5n7uP7xH3sETp4WfSKZQLajqVEBR8iyw9PhzFqFHFdw7sixrRYwC3Mmxmfei6Tm0CmljKgc+dVrzbzcTkdtJ6VJfqGelvJnKoU5+8Ip+wAHdHFv29hUUJEef6DV1eYgwromzgKfa+fieBBTwE0DWmIb6w8/9VClDFKKnnrXFAPPmt+W4SoYc1hIr7e/QNw/2XhKe482bz68QXOWKiGPAX1R2Hu6ew7mfgFU92girN/Cfncq1i0pyskrE17A8F7r0KDKecUBB1DaW+Pf4xUDr5CWm2124pkS8BQOoMcSiCOzjdIQRfDg6gVwdUcmsX3jXmroV1I9euHy2Xb+6Lfm199XkHrnHo9iFdoI2G67SkQHSiv2IijBF3+FmVBxyfQVvQpZmuspd8F5QErfgZE1wAE0xRolsUmRHuJqRnak5j52a20jUhLwTcs2TiUcECvNkEplrvgWUiAaW4Qx5jQLebhPupnD3aN1bvHfVc6pP0Aa0cLKSzeTSBg3B+BbadFJbypBX92ewWQ0D/WscI6qIAqnur1omsUJwhkpC4lkMo8GERhdJjl6bVoHNeHQdsy9/8IK030Ly3j2/lwoIUZ5WukAaqw2yQamfAQ48HnTXWf0dkZ44s2gf3kTdKnfP4EW+bYVH2+q6tPUI+hHM4YwRd69xO1s/u/HES0hYVNuToT/r9YAdBzCTYZNEIcEq50E21ZqXz91EaMXZwDnXT2/lx0OSZo= -e none https://<AccountID>.dkr.ecr.us-east-1.amazonaws.com
[root@samal-dimdung3 ~]#

3. If you want to build docker from Dockerbuild 
[root@samal-dimdung3 ~]# docker build -t devopstest .

4. Pull images from RHN 
[root@samal-dimdung3 ~]# docker pull registry.access.redhat.com/rhel7/rhel
Using default tag: latest
Trying to pull repository registry.access.redhat.com/rhel7/rhel ...
latest: Pulling from registry.access.redhat.com/rhel7/rhel

154dc369ca0d: Pull complete
e6b5b6e3c142: Pull complete
Digest: sha256:eda7f2c5a9d051137a9c0369f675fff00f296ea9394763fb93f2a08c9202cade
[root@samal-dimdung3 ~]# docker images
REPOSITORY                              TAG                 IMAGE ID            CREATED             SIZE
registry.access.redhat.com/rhel7/rhel   latest              41a4953dbf95        5 weeks ago         192.5 MB
[root@samal-dimdung3 ~]#

5. Apply a tag to an image 
[root@samal-dimdung3 ~]# docker tag registry.access.redhat.com/rhel7/rhel:latest <AWS-AccountID>.dkr.ecr.us-east-1.amazonaws.com/devopstest:rhel7base
6. Push to an ECR repository
[root@samal-dimdung3 ~]# docker push <AWS-AccountID>.dkr.ecr.us-east-1.amazonaws.com/devopstest:rhel7base
The push refers to a repository [<AWS-AccountID>.dkr.ecr.us-east-1.amazonaws.com/devopstest]
9ca8c628d8e7: Pushed
827264d42df6: Pushed
rhel7base: digest: sha256:72364ad16b483d3a7da027d8c89616d872b1a777d98969974079699e5e86e83e size: 737
[root@samal-dimdung3 ~]#

7. Docker pull into local :
[root@samal-dimdung3 ~]# docker pull <AWS-ACCOUNT-ID>.dkr.ecr.us-east-1.amazonaws.com/devopstest:rhel7base
Trying to pull repository <AWS-ACCOUNT-ID>.dkr.ecr.us-east-1.amazonaws.com/devopstest ...
rhel7base: Pulling from <AWS-ACCOUNT-ID>.dkr.ecr.us-east-1.amazonaws.com/devopstest

3436c67883ad: Pull complete
c85416a3d375: Pull complete
Digest: sha256:72364ad16b483d3a7da027d8c89616d872b1a777d98969974079699e5e86e83e
[root@samal-dimdung3 ~]#

5. Pull into an ECS Container
