To install the AWS CLI and Docker and for more information on the steps below, visit the ECR documentation page.
1) Retrieve the docker login command that you can use to authenticate your Docker client to your registry:
aws ecr get-login --region us-east-1

2) Run the docker login command that was returned in the previous step.
3) Build your Docker image using the following command. For information on building a Docker file from scratch see the instructions here. You can skip this step if your image is already built:
docker build -t deveopstest .

4) After the build completes, tag your image so you can push the image to this repository:
docker tag deveopstest:latest 89000000000293.dkr.ecr.us-east-1.amazonaws.com/deveopstest:latest

5) Run the following command to push this image to your newly created AWS repository:
docker push 89000000000293.dkr.ecr.us-east-1.amazonaws.com/deveopstest:latest
