[root@ip-10-76-32-9 ~]# cat fips.yml 
---
- hosts: localhost
  user: root
  sudo: no

  tasks:
    - name: Set to prelink PRELINKING=no
      lineinfile: dest=/etc/sysconfig/prelink regexp=^PRELINKING= line=PRELINKING=no

    - name: Existing Prelinking, if any
      shell: prelink -u -a

    - name: Recreate the initramfs file
      shell: mkinitrd --with-fips -f /boot/initrd-$(uname -r).img $(uname -r)

    - name: Add fips=1 at the end of the Kernl Line
      lineinfile: dest=/etc/grub.conf
        backup=True
        backrefs=True
        state=present
        regexp='(^\s+kernel(\s+(?!fips=1)[\w=/\-\.]+)*)\s*$'
        line='\1 fips=1'

    - name: Add boot=/dev/hda1 the end of the Kernl Line
      lineinfile: dest=/etc/grub.conf
        backup=True
        backrefs=True
        state=present
        regexp='(^\s+kernel(\s+(?!boot=/dev/hda1)[\w=/\-\.]+)*)\s*$'
        line='\1 boot=/dev/hda1'
[root@ip-10-76-32-9 ~]# 
