language: python
python: '2.7'
sudo: false
env:
- PYTHONUNBUFFERED=1
before_install:
- openssl aes-256-cbc -K $encrypted_9dd3cd511634_key -iv $encrypted_9dd3cd511634_iv -in secrets.tgz.enc -out secrets.tgz -d
- tar xzf secrets.tgz
- echo -e "Host *\n\tStrictHostKeyChecking no\n" >> ~/.ssh/config
install:
- pip install -U pip
- pip install ansible
- pip install rackspace-novaclient
- pip install pyrax
script:
- ansible-playbook -i hosts playbook.yml --syntax-check
- ansible-playbook --private-key=travis-key -v -i test-hosts test-rackspace.yml
- rm -f secrets.tgz .pyrax travis-key
