---
- hosts: localhost
  connection: local
  gather_facts: False
  tasks:

    - name: Build a new cloud server
      action:
        module: rax
        credentials: .pyrax
        name: "cis-rhel-ansible-testing"
        flavor: general1-2
        image: aa68fd54-2f9a-42c3-9901-4035e2738830
        key_name: travis-key
        wait: yes
        region: IAD
        state: present
        networks:
          - private
          - public
        group: raxhosts
      register: rax

    - name: Add new instance to host group
      local_action:
          module: add_host
          hostname: "{{ item.accessIPv4 }}"
          groupname: raxhosts
      with_items: rax.instances

- name: Wait for server to come online
  hosts: raxhosts
  user: root
  gather_facts: false
  tasks:

    - name: Wait for server to come online
      wait_for: >
        port=22
        timeout=300

- name: Test the ansible playbook on the remote host
  hosts: raxhosts
  user: root
  tasks:

    # This is mainly to prevent shenanigans with people trying to hop
    # into the VM while it's building at travis-ci. ;)
    - name: Disable ssh authentication with passwords
      lineinfile:
        dest: /etc/ssh/sshd_config
        regexp: "^#?PasswordAuthentication"
        line: "PasswordAuthentication no"

    - name: Restart sshd
      service:
        name: sshd
        state: restarted

    - name: Install ansible
      yum:
        name: ansible
        state: latest

    - name: Make a directory to hold the ansible scripts
      file:
        path: /root/ansible-role-cis/
        state: directory

    - name: Copy over files
      copy:
        src: "{{ item }}"
        dest: /root/ansible-role-cis/
      with_items:
        - ansible.cfg
        - hosts
        - playbook.yml
        - roles

    - name: Run the ansible playbook
      shell: "cd /root/ansible-role-cis && ansible-playbook -i hosts playbook.yml"

- hosts: localhost
  connection: local
  gather_facts: False
  tasks:

    - name: Delete the cloud server
      action:
        module: rax
        credentials: .pyrax
        name: "cis-rhel-ansible-testing"
        flavor: general1-2
        image: aa68fd54-2f9a-42c3-9901-4035e2738830
        key_name: travis-key
        wait: yes
        region: IAD
        state: present
        group: raxhosts
        count: 0
        exact_count: yes
        networks:
          - private
          - public
      register: rax
