---
- hosts: 10.176.32.119
  user: ec2-user
  sudo: yes

  tasks:
  # Create a ext4 filesystem on /dev/xvdb, /dev/xvde, /dev/xvdf, /dev/xvdg, /dev/xvdh
  - filesystem: fstype=ext4 dev=/dev/xvdb
  - filesystem: fstype=ext4 dev=/dev/xvdc
  - filesystem: fstype=ext4 dev=/dev/xvdd
  - filesystem: fstype=ext4 dev=/dev/xvde
  - filesystem: fstype=ext4 dev=/dev/xvdf

  # Creating Mount point for /u01, /u02, /u03, /u98 and /u98
  - file: path=/u01 state=directory mode=0755
  - file: path=/u02 state=directory mode=0755
  - file: path=/u03 state=directory mode=0755
  - file: path=/u98 state=directory mode=0755
  - file: path=/u99 state=directory mode=0755

  # Update the /etc/fstab  for /u03 and  /dev/xvdf
  #- mount: name=/u03 src=/dev/xvdf  fstype=ext4 state=present
  - mount: name=/u01 src=/dev/xvdb  fstype=ext4 state=mounted
  - mount: name=/u02 src=/dev/xvdc  fstype=ext4 state=mounted
  - mount: name=/u03 src=/dev/xvdd  fstype=ext4 state=mounted
  - mount: name=/u98 src=/dev/xvde  fstype=ext4 state=mounted
  - mount: name=/u99 src=/dev/xvdf  fstype=ext4 state=mounted

  # Add oracle user
  - user: name=oracle shell=/bin/bash state=present

  # Change owner and group of mount point
  - file: path=/u01 owner=oracle group=oracle
  - file: path=/u02 owner=oracle group=oracle
  - file: path=/u03 owner=oracle group=oracle
  - file: path=/u98 owner=oracle group=oracle
  - file: path=/u99 owner=oracle group=oracle
