- name: provision stack
  hosts: localhost
  connection: local
  gather_facts: false

# Basic task example
  tasks:
  - name: launch ansible cloudformation example
    cloudformation: >
      stack_name="ansible-cloudformation" state=present
      region=us-east-1 disable_rollback=true
      template=files/cloudformation-example-ec2.json
    args:
      template_parameters:
        KeyName: djohnson
    register: stack
