---
#Provision some instances:
- hosts: localhost
  connection: local
  gather_facts: False

  vars_files:
  - group_vars/all
 
  tasks:
  - name: Launch webserver instances
    ec2: >
     access_key="{{ ec2_access_key }}"
     secret_key="{{ ec2_secret_key }}"
     keypair="{{ ec2_keypair }}"
     group="{{ ec2_security_group }}"
     type="{{ ec2_instance_type }}"
     image="{{ ec2_image }}"
     region="{{ ec2_region }}"
     zone="{{ item }}"
     instance_tags="{'ansible_group':'demo', 'type':'{{ ec2_instance_type }}', 'group':'{{ ec2_security_group }}', 'Name':'demo-dj'}"
     count="{{ ec2_instance_count }}"
     wait=true
    register: ec2
    with_items:
      - us-east-1b
      - us-east-1c

