---
# Linux Utilities
 tasks:
  - name: Add X11
    yum:
      name="@X Window System"
      state=present
  - name: Add XTerm
    yum:
      name="xterm"
      state=present
  - name: Install repo
    command: rpm -Uvh http://rpms.famillecollet.com/enterprise/remi-release-6.rpm
    ignore_errors: yes
  - name: Add Mozilla
    yum:
      name="firefox"
      state=present
  - name: Install xorg-x11-auth
    command: yum install -y xorg-x11-auth
	
  - name: Install org-xorg-x11-fonts
    command: yum install -y xorg-x11-fonts-*
	
  - name: Install xorg-x11-utils
    command: yum install -y xorg-x11-utils
    
  - name: Install xclock 
    command: yum install -y xlcock 
    
