---
# file: tasks/section-02-level-2.yml

# NOTE: what-if we use a template instead of tasks???
# state=touch always returns "changed: True",
# so should we override the changed results ?

- name: Check if /etc/modprobe.d/CIS.conf exists
  stat: path=/etc/modprobe.d/CIS.conf follow=True
  register: modprobe_cis_path
  tags:
    - section2.19
    - section2.20
    - section2.21
    - section2.22
    - section2.23
    - section2.24
    - section2.25

- name: Create /etc/modprobe.d/CIS.conf
  file: path=/etc/modprobe.d/CIS.conf state=touch owner=root group=root mode=0644
  when: not modprobe_cis_path.stat.exists
  tags:
    - section2.19
    - section2.20
    - section2.21
    - section2.22
    - section2.23
    - section2.24
    - section2.25

- name: Check if /etc/modprobe.d/CIS.conf has been created and it exists
  stat: path=/etc/modprobe.d/CIS.conf follow=True
  register: modprobe_cis_path
  tags:
    - section2.19
    - section2.20
    - section2.21
    - section2.22
    - section2.23
    - section2.24
    - section2.25

- name: 2.19 Disable Mounting of freevxfs Filesystems (Not Scored)
  lineinfile: dest=/etc/modprobe.d/CIS.conf line="install cramfs /bin/true" state=present
  when: modprobe_cis_path is defined and modprobe_cis_path.stat.exists
  tags:
    - notscored
    - section2.19

- name: 2.20 Disable Mounting of jffs2 Filesystems (Not Scored)
  lineinfile: dest=/etc/modprobe.d/CIS.conf line="install jffs2 /bin/true" state=present
  when: modprobe_cis_path is defined and modprobe_cis_path.stat.exists
  tags:
    - notscored
    - section2.20

- name: 2.21 Disable Mounting of hfs Filesystems (Not Scored)
  lineinfile: dest=/etc/modprobe.d/CIS.conf line="install hfs /bin/true" state=present
  when: modprobe_cis_path is defined and modprobe_cis_path.stat.exists
  tags:
    - notscored
    - section2.21

- name: 2.22 Disable Mounting of hfsplus Filesystems (Not Scored)
  lineinfile: dest=/etc/modprobe.d/CIS.conf line="install hfsplus /bin/true" state=present
  when: modprobe_cis_path is defined and modprobe_cis_path.stat.exists
  tags:
    - notscored
    - section2.22

- name: 2.23 Disable Mounting of squashfs Filesystems (Not Scored)
  lineinfile: dest=/etc/modprobe.d/CIS.conf line="install squashfs /bin/true" state=present
  when: modprobe_cis_path is defined and modprobe_cis_path.stat.exists
  tags:
    - notscored
    - section2.23

- name: 2.24 Disable Mounting of udf Filesystems (Not Scored)
  lineinfile: dest=/etc/modprobe.d/CIS.conf line="install udf /bin/true" state=present
  when: modprobe_cis_path is defined and modprobe_cis_path.stat.exists
  tags:
    - notscored
    - section2.24

- name: 2.25 Disable Automounting (Scored)
  stat: path=/etc/init/autofs.conf follow=True
  register: autofs_path
  tags:
    - scored
    - section2.25

- name: 2.25 Disable Automounting (Scored)
  service: name=autofs state=stopped enabled=no
  when: autofs_path is defined and autofs_path.stat.exists
  ignore_errors: yes
  tags:
    - scored
    - section2.25

# vim: set sw=2 ts=2:
