---
#file: tasks/section-10-level-1.yml

- name: 10.1 Set Shadow Password Suite Parameters (/etc/login.defs)
  debug: msg="*** While a majority of the password control parameters have been moved to PAM, some parameters are still available through the shadow password suite"
  tags:
    - section10.1

- name: 10.1.1 Set Password Expiration Days (Scored)
  lineinfile: dest=/etc/login.defs regexp="^PASS_MAX_DAYS" line="PASS_MAX_DAYS {{ pass_max_days }}" state=present
  tags:
    - scored
    - section10.1
    - section10.1.1

- name: 10.1.2 Set Password Change Minimum Number of Days (Scored)
  lineinfile: dest=/etc/login.defs regexp="^PASS_MIN_DAYS" line="PASS_MIN_DAYS {{ pass_min_days }}" state=present
  tags:
    - scored
    - section10.1
    - section10.1.2

- name: 10.1.3 Set Password Expiring Warning Days (Scored)
  lineinfile: dest=/etc/login.defs regexp="^PASS_WARN_AGE" line="PASS_WARN_AGE {{ pass_warn_age }}" state=present
  tags:
    - scored
    - section10.1
    - section10.1.3

- name: 10.2 Disable System Accounts (Scored)
  copy: src=disable_system_accounts.sh dest=/root/disable_system_accounts.sh owner=root group=root mode=0700
  when: disable_system_accounts == "no"
  tags:
    - scored
    - section10.2

- name: 10.2 Disable System Accounts (Scored)
  shell: /bin/bash /root/disable_system_accounts.sh
  when: disable_system_accounts == "no"
  tags:
    - scored
    - section10.2

- name: 10.3 Set Default Group for root Account (Scored)
  user: name=root group=root uid=0 state=present
  tags:
    - scored
    - section10.3

- name: 10.4 Set Default umask for Users (Scored)
  lineinfile: dest=/etc/login.defs regexp="^UMASK" line="UMASK 077" state=present
  tags:
    - scored
    - section10.4

- name: 10.5 Lock Inactive User Accounts (Scored)
  debug: msg="*** Evaluate your infrastructure first, before locking inactive accounts"
  tags:
    - scored
    - section10.5

# vim: set sw=2 ts=2:
