---
#Provision some instances:
- hosts: localhost
  connection: local
  gather_facts: False

  vars_files:
  - group_vars/all
 
  tasks:
  - name: Launch webserver instances
    rax: >
     name="demo-webserver"
     flavor="performance1-2"
     image="68d5cc64-cb68-4275-9ede-9b062f7be070"
     region="ORD"
     wait=yes
     state=present
     count={{ rax_instance_count }}
     auto_increment=yes
     keypair="davejohnson-demo"
     group="webservers"
    register: rax

#  - name: Launch database instance
#    ec2: >
#     access_key="{{ ec2_access_key }}"
#     secret_key="{{ ec2_secret_key }}"
#     keypair="{{ ec2_keypair }}"
#     group="{{ ec2_security_group }}"
#     type="{{ ec2_instance_type }}"
#     image="{{ ec2_image }}"
#     region="{{ ec2_region }}"
#     instance_tags="{'ansible_group':'dbservers', 'type':'{{ ec2_instance_type }}', 'group':'{{ ec2_security_group }}'}"
#     count="1"
#     wait=true
#    register: ec2
#
#  - name: Launch load balancing instance
#    ec2: >
#     access_key="{{ ec2_access_key }}"
#     secret_key="{{ ec2_secret_key }}"
#     keypair="{{ ec2_keypair }}"
#     group="{{ ec2_security_group }}"
#     type="{{ ec2_instance_type }}"
#     image="{{ ec2_image }}"
#     region="{{ ec2_region }}"
#     instance_tags="{'ansible_group':'lbservers', 'type':'{{ ec2_instance_type }}', 'group':'{{ ec2_security_group }}'}"
#     count="1"
#     wait=true
#    register: ec2

#  - name: Launch monitoring instance
#    ec2: >
#     access_key="{{ ec2_access_key }}"
#     secret_key="{{ ec2_secret_key }}"
#     keypair="{{ ec2_keypair }}"
#     group="{{ ec2_security_group }}"
#     type="{{ ec2_instance_type }}"
#     image="{{ ec2_image }}"
#     region="{{ ec2_region }}"
#     instance_tags="{'ansible_group':'monitoring', 'type':'{{ ec2_instance_type }}', 'group':'{{ ec2_security_group }}'}"
#     count="1"
#     wait=true
#    register: ec2

